name: Trigger Jenkins Joob

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins via API
        run: |
          curl -X POST http://localhost:8080/job/deploy_node_job/build \
            --user "admin:${{ secrets.JENKINS_TOKEN }}"
